# Generated by Django 4.0.2 on 2022-03-08 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_article_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.CharField(blank=True, choices=[('Business', 'Business'), ('Culinary', 'Culinary'), ('Culture', 'Culture'), ('Health', 'Health'), ('Literature', 'Literature'), ('Other', 'Other'), ('Politics', 'Politics'), ('Sports', 'Sports')], max_length=30, null=True),
        ),
    ]
