# Generated by Django 4.0.2 on 2022-03-12 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_alter_article_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
